language: node_js
node_js: 5.5.0
script:
- npm install
- npm test
- cd resources && tar -zcvf dummy.tar.gz dummy && cd ..
deploy:
  provider: releases
  api_key:
    secure: SNMwZm2PXqfg8712LemweIWJRk3f5Da71/i1GttvwKrnMove+qxGAJC8u6objKWPRwb1wOShgHCsJ1NnPSf7d3iYV0xluxuzkg4hHki6kvXbxayBX7xIBzOSLWfJ/IwxGTq42ezdn4FfZ+B6w5HjJowo3AOwv+1YqvC+mt5UWkrneNiad1xUgUL5TG8kvFKbdElMs3KKHSf9Q8sorZwjYPUiCH8aBlrv3EaXabkeX4HaqJz+uxpqwRxkMD98h+5GxUs/SGNCzfBg3dblJuWj+Sxn3HWCeaOYs0Ntzd6jGT342Iky3wwrj976qSng6Y2eKyUB9OqOtWGPHj/369BoobSC68H0Qnd1o1Vvqn+D8rxvuJAgjn1qlD0klSF90tv9jyN3RG+5/QkyLTlk+7Lm70aMShiVasgbwOe5ZksbRSdGdn2REXBDFI2s4oxnmjhV1o8M0XJ6tU5ILhKXTFGKZHNA1TQxPCSVbR8AhMFA94k17bfIse0olO3Ds4O6nLhBro0idMgGJVCA1R4RI0njqXEBeh9GExp+hMPZTSySy/lHq+UwDXlvBvYc3Hl2Cvx7NaMHEAjiO/rN3JKnpO3nqCHkx3BN5zozGKIb40Szf3/pCs+cCDXICCILIzZjEdpn+5NutafFp+ANnhDmddMLpykRtWJVA5HeVTFlbDA7GEA=
  skip_cleanup: true
  file: resources/dummy.tar.gz
  on:
    repo: schreiben/node-grd
